//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week8Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageTag
    {
        public int TagID { get; set; }
        public int UserImageID { get; set; }
        public string Tag { get; set; }
    
        public virtual UserImage UserImage { get; set; }
    }
}
