//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week8Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserImage()
        {
            this.ImageTags = new HashSet<ImageTag>();
        }
    
        public int ImageID { get; set; }
        public int StateID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTaken { get; set; }
        public byte[] ImageByte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImageTag> ImageTags { get; set; }
        public virtual State State { get; set; }
    }
}
